// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oohjgdstwkupdswpwoqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vaGpnZHN0d2t1cGRzd3B3b3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjM0MjQsImV4cCI6MjA2ODY5OTQyNH0.3rpH_g05y9Y8skj88uXJqZKnAwBU5WfW5jMN2GrlzQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});