// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbaprijrjqbdxgfptbhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiYXByaWpyanFiZHhnZnB0YmhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTAwNzEsImV4cCI6MjA2ODY2NjA3MX0.aZQYcws_QUHujmfUc2ebYS0kUoILzkt9pGwOgyQxXmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
